dir = "Den_to_Papuan"
ref_pop = "DenA"
maf_threshold = 0.05

[sim]
sequence_length = 100_000
min_allele_frequency = 0.01

[sim.tranche]
"not AI" = [
	"HomSap/PapuansOutOfAfrica_10J19/Neutral/slim",
	"HomSap/PapuansOutOfAfrica_10J19/Sweep/Papuan",
]

AI = [
	"HomSap/PapuansOutOfAfrica_10J19/AI/Den1_to_Papuan",
	"HomSap/PapuansOutOfAfrica_10J19/AI/Den2_to_Papuan",
]

[sim.extra]
"DFE" = ["HomSap/PapuansOutOfAfrica_10J19/DFE"]

[vcf]
chr = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
	20, 21, 22 ]
file = "misc/vcf/HGDP.1000g.archaic.IGDP.${chr}.bcf"
phased = false

[pop]
NeaA = ["AltaiNeandertal"]
DenA = ["Denisova"]
# Although the label 'Papuan' has been used here, the IGDP dataset includes
# non-Papuan populations from throughout Island South Sast Asia, and the
# population label 'Melanesian' would have been a better choice here.
Papuan = "misc/IGDP_OCEANIA.indlist"
YRI = "misc/YRI.indlist"

[train]
num_rows = 256
epochs = 3
batch_size = 64
model = "cnn"

[train.af_filter]
pop = "Papuan"
modelspec = "HomSap/PapuansOutOfAfrica_10J19/AI"
AF = 0.25

[train.cnn]
n_conv = 7
n_conv_filt = 16
filt_size_x = 4
filt_size_y = 4
n_dense = 0
dense_size = 0

[calibrate.weights]
"HomSap/PapuansOutOfAfrica_10J19/Neutral/slim" = 1
"HomSap/PapuansOutOfAfrica_10J19/Sweep/Papuan" = 0.1
"HomSap/PapuansOutOfAfrica_10J19/AI/Den1_to_Papuan" = 0.01
"HomSap/PapuansOutOfAfrica_10J19/AI/Den2_to_Papuan" = 0.01

[apply]
batch_size = 256
step = 20_000
max_missing_genotypes = 0.1
min_seg_sites = 20

