dir = "test-example"
ref_pop = "Nea"
maf_threshold = 0.05

[sim]
sequence_length = 100_000
min_allele_frequency = 0.01

[sim.tranche]
"not AI" = [
	"HomSap/HomininComposite_4G20/Neutral/slim",
	"HomSap/HomininComposite_4G20/Sweep/CEU",
]

AI = [
	"HomSap/HomininComposite_4G20/AI/Nea_to_CEU",
]

[sim.extra]
#DFE = ["HomSap/HomininComposite_4G20/DFE"]

[vcf]
chr = [ 22 ]
file = "examples/HGDP.1000g.archaic.${chr}.1mb.vcf.gz"

[pop]
Nea = ["AltaiNeandertal", "Vindija33.19"]
CEU = "misc/CEU.indlist"
YRI = "misc/YRI.indlist"

[train]
train_frac = 0.5
num_rows = 32
epochs = 1
batch_size = 64
model = "cnn"

[train.af_filter]
pop = "CEU"
modelspec = "HomSap/HomininComposite_4G20/AI/Nea_to_CEU"
AF = 0

[train.cnn]
n_conv = 3
n_conv_filt = 16
filt_size_x = 4
filt_size_y = 4
n_dense = 0
dense_size = 0

[calibrate.weights]
"HomSap/HomininComposite_4G20/Neutral/slim" = 1
"HomSap/HomininComposite_4G20/Sweep/CEU" = 0.1
"HomSap/HomininComposite_4G20/AI/Nea_to_CEU" = 0.1

[apply]
batch_size = 256
step = 20_000
max_missing_genotypes = 0.1
min_seg_sites = 20
